### ISSUE TITLE
Not seeing folder actual name nor some RVT files

### ISSUE THREAD

**Issue by jmcouffin** [Autodesk-Forge/forge-bim360-issues#13]
Hi, 
Nice sample @augustogoncalves 
I managed making an app from your base code but it does not display the proper name of some folders and does not show some of the rvt files
for référence https://github.com/Autodesk-Forge/forge-bim360-issues
![image](https://user-images.githubusercontent.com/7872003/133394455-1e48258f-dd7d-4df2-ae8b-01d2463cfe63.png)
you visual reports sample works well. the issue one does not...
I will start looking into it but being pretty new to it, It might take some time

**Comment by augustogoncalves** [comment]
Fixed on https://github.com/Autodesk-Forge/forge-bim360-issues/commit/bebd9d8ea6bc4b3c931351d99e145ecd42ace01e

**Comment by jmcouffin** [comment]
Not quite yet unfortunately
it fixed the non-display of Revit files but not the folder name
I still get the 'New Folder' instead of the folder name.
I tried deleting cache, CTRL+F5 as well, signing in and out again => no go
